# Generated by Django 2.2.8 on 2020-01-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200129_0205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingReview',
            new_name='RatingAndReview',
        ),
    ]
