# Generated by Django 2.2.8 on 2020-02-04 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200204_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingandreview',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date joined'),
        ),
    ]
