# Generated by Django 2.2.8 on 2020-02-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_ratingandreview_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingandreview',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
    ]
